test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  collation: utf8_unicode_ci
  database: blog_new
  pool: 5
  username: root
  password: "123456"

development:
  adapter: mysql2
  encoding: utf8
  collation: utf8_unicode_ci
  reconnect: true
  database: blog_new
  host: 127.0.0.1
  pool: 5
  username: root
  password: "123456"

production:
  adapter: mysql2
  encoding: utf8
  collation: utf8_unicode_ci
  reconnect: true
  database: blog_new
  pool: 5
  username: root
  password: "123456"
